### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Odywan55** [ShariqMush/react-native-fullscreenvideo-player#2]
Hello, i'v done as you wrote, and it works with issues (((

In player_fullscreen.xml  i have such error : 
<img width="797" alt="screen shot 2017-10-12 at 20 46 33" src="https://user-images.githubusercontent.com/13364000/31510885-89a6b05c-af8e-11e7-90cb-a9cdf0d6bbd0.png">

java.lang.NoSuchFieldError: TextAppearance_textAllCaps
	at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:51)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:51)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:475)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:262)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:213)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadClass(LayoutlibCallbackImpl.java:193)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:333)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:152)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:222)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:95)
	at com.android.layoutlib.bridge.bars.StatusBar.<init>(StatusBar.java:67)
	at com.android.layoutlib.bridge.impl.Layout.createStatusBar(Layout.java:224)
	at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:146)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:301)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

and it is not scaling 
<img width="836" alt="screen shot 2017-10-12 at 21 12 23" src="https://user-images.githubusercontent.com/13364000/31512002-2d2ed328-af92-11e7-88da-8a321427834e.png">

**Comment by Odywan55** [comment]
change to this to make any video fit full screen in player_fullscreen.xml

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    tools:context=".VideoActivity">

    <VideoView
        android:id="@+id/videoView"
        android:layout_alignParentTop="true"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentRight="true"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        />
</RelativeLayout>
